const DATA = [
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    {
        id:1,
        urlImage:'https://icon-library.com/images/clash-of-clans-app-icon/clash-of-clans-app-icon-21.jpg',
        author:'Admin',
        title:'App Name 1',
        rating:'4.2',
        paragraph:'Lorem ipsum dolor sit amet.',
        download: "120k",
        Link_Download:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
        Link_LoadingPage:'https://download1074.mediafire.com/k3oc044okg8g/t1ulq9k5utt6mgo/FORGIVE+ME+158+BPM+%28C+major%29.wav',
    },
    
];

export default DATA;